define({
  "taskUrl": "URL de la tâche",
  "setTask": "Définir",
  "setTaskPopupTitle": "Définir une tâche",
  "validate": "Définir",
  "inValidGPService": "Saisissez un service de géotraitement valide.",
  "noOutputParameterWithGeometryType": "Le service de géotraitement sélectionné doit avoir au moins un paramètre en sortie avec un type de géométrie spécifié. Sélectionnez un service de géotraitement différent.",
  "invalidOutputGeometry": "Le type de géométrie en sortie du service de géotraitement sélectionné n’est pas compatible avec les paramètres du projet. Impossible de stocker les résultats du service de géotraitement.",
  "GPFeatureRecordSetLayerERR": "Saisissez un service de géotraitement avec des entrées de type 'GPFeatureRecordSetLayer' uniquement.",
  "invalidInputParameters": "Le nombre de paramètres en entrée est inférieur à 1 ou supérieur à 3. Saisissez un service de géotraitement valide.",
  "projectSetting": {
    "title": "Paramètres du projet",
    "note": "Remarque : les paramètres du projet sont facultatifs une fois que l’utilisateur configuré peut stocker le projet dans les couches de carte web souhaitées, avec la zone de panne réseau et les paramètres en entrée. L’utilisateur peut stocker d’autres paramètres en sortie depuis le groupe “Sortie” de l’onglet “Entrée/Sortie”.",
    "projectPolygonLayer": "Couche surfacique du projet",
    "outputParameterName": "Nom du paramètre en sortie",
    "projectPointLayer": "Couche de points du projet",
    "selectLabel": "Sélectionner",
    "polygonLayerHelp": "<p>Les couches de polygones avec les conditions suivantes s’afficheront :<br/><ul><li>La couche doit disposer des fonctionnalités de mise à jour Créer, Supprimer et Mettre à jour</li><li>La couche doit posséder 2 champs avec exactement les noms et types de données suivants :</li><ul><li>name (champ de type chaîne)</li><li>globalid (champ de type GlobalID)</li></ul></ul><p/>",
    "outputParameterHelp": "<p>Les couches surfaciques en sortie issues de l’URL de la tâche s’afficheront<p/>",
    "pointLayerHelp": "<p>Les couches de points avec les conditions suivantes s’afficheront : <br/><ul><li>La couche doit disposer des fonctionnalités de mise à jour Créer, Supprimer et Mettre à jour</li><li>La couche doit posséder 2 champs avec exactement les noms et types de données suivants :</li><ul><li>inputtype (champ de type chaîne)</li><li>projectid (champ de type GUID)</li></ul></ul><p/>"
  },
  "inputOutputTab": {
    "flag": "Drapeau",
    "barrier": "Interruption",
    "skip": "Ignorer",
    "title": "Entrée",
    "inputTooltip": "Info-bulle",
    "typeText": "Type",
    "symbol": "Symbole",
    "summaryEditorText": "Texte de résumé",
    "summaryTextTitle": "Indiquez le texte à afficher dans l’onglet en entrée"
  },
  "summaryTab": {
    "title": "Sortie",
    "summaryFieldsetText": "Paramètres de résumé",
    "inputOutput": "Entrée/Sortie",
    "field": "Champ",
    "operator": "Opérateur",
    "inputOperatorCountOption": "Total",
    "outputOperatorCountOption": "Total",
    "outputOperatorSkipCountOption": "Nombre d’entités ignorées",
    "fieldOperatorSumOption": "Somme",
    "fieldOperatorMinOption": "Min",
    "fieldOperatorMaxOption": "Max",
    "fieldOperatorMeanOption": "Moyenne",
    "expressionAddButtonText": "Ajouter",
    "expressionVerifyButtonText": "Vérifier",
    "summaryEditorText": "Texte de résumé",
    "zoomText": "Zoom automatique après le parcours",
    "summarSettingTooltipText": "Ajouter le nombre total d’entrées/sorties",
    "symbol": "Symbole",
    "outputParametersText": "Paramètres en sortie",
    "skipText": "Peut être ignoré",
    "visibilityText": "Visibles",
    "exportToCsvText": "Exporter au format CSV",
    "settitngstext": "Réglages",
    "saveToLayerText": "Enregistrer dans une couche (facultatif)",
    "inputLabel": "Etiquette",
    "inputTooltip": "Info-bulle",
    "outputDisplay": "Texte d’affichage",
    "addFieldTitle": "Ajouter un champ",
    "setScale": "Définir l’échelle",
    "enterDisplayText": "Entrer le texte d’affichage",
    "saveToLayerHelp": "<p>La couche avec les conditions suivantes s’affichera : <br/><ul><li>La couche doit disposer des fonctionnalités de mise à jour “Créer”, “Supprimer” et “Mettre à jour”</li><li>La couche doit posséder deux champs avec le nom et le type de données suivants :</li><ul><li>parametername (champ de type chaîne)</li><li>projectid (champ de type GUID)</li></ul></ul><p/>",
    "exportToCsvDisplayText": "CSV",
    "summaryTextTitle": "Indiquez le texte de résumé à afficher sur l’onglet en sortie",
    "addSummaryItemsTitle": "Ajouter des éléments de résumé"
  },
  "validationErrorMessage": {
    "webMapError": "Aucune couche disponible dans la carte web. Sélectionnez une carte web valide.",
    "inputTypeFlagGreaterThanError": "Une seule entrée de type indicateur est possible.",
    "inputTypeFlagLessThanError": "Au moins une entrée de type indicateur est requise.",
    "inputTypeBarrierErr": "Une seule entrée de type interruption est possible.",
    "inputTypeSkipErr": "Une seule entrée de type ignorer est possible.",
    "displayTextForButtonError": "Le texte d’affichage pour le bouton 'Exécuter' ne peut pas être vide.",
    "UnableToLoadGeoprocessError": "Chargement du service de géotraitement impossible.",
    "invalidSummaryExpression": "Expression non valide.",
    "validSummaryExpression": "Opération réussie !",
    "invalidProjectSettings": "Paramètres de projet non valides.<br/> Sélectionnez une valeur valide dans '${projectSetting}'."
  },
  "hintText": {
    "labelTextHint": "Astuce : fournissez une étiquette d’affichage pour le volet généré du paramètre en sortie.",
    "displayTextHint": "Astuce : ceci apparaîtra dans le volet des détails pour ce paramètre en sortie.",
    "inputTextHint": "Astuce : créez votre expression ci-dessous à l’aide du bouton Ajouter des éléments de résumé.",
    "expressionHint": "Astuce : sélectionnez des éléments et cliquez sur Ajouter pour construire une expression."
  }
});